export const ITEM_SPRITES = {
  sword: `
    ....SS....
    ....SS....
    ....SS....
    ....SS....
    ....BB....
    ...BBBB...
    ....BB....
  `.trim().split('\n').map(row => row.trim()),
  
  shield: `
    ..BBBBBB..
    .BBBBBBBB.
    BBBBBBBBBB
    .BBBBBBBB.
    ..BBBBBB..
    ...BBBB...
    ....BB....
  `.trim().split('\n').map(row => row.trim())
};